# 所有服务的全局配置

# 公共配置地址
base:
  auth:
    server: http://192.168.1.93:9001
  mysql:
    url: jdbc:mysql://47.96.167.246:3306
  redis:
    host: 47.96.167.246
    port: 6379
    database: 0
    password: 

#token 失效时间 单位：分钟
access-token:
  validityseconds: 300
  refreshvalidityseconds: 300

server:
  tomcat:
    max-threads: 200 # Maximum amount of worker threads.
    min-spare-threads: 10 # Minimum amount of worker threads

# actuator端点配置
management:
  security:
    # 不使用actuator默认的安全验证，可以直接访问开启的端点
    enabled: false
  # 为actuator端点设置前缀,一般情况下都需要设置以便与业务path区分开来
  context-path: /management

# eureka配置
eureka:
  client:
    healthcheck:
      enabled: true
    # eureka客户端从eureka服务器注册表中获取服务注册信息的时间间隔（s），默认为30秒,开发阶段调小
    registry-fetch-interval-seconds: 10
  instance:
      # 注册服务ip到eureka server上
      prefer-ip-address: true
      # 自定义服务实例id
      instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${server.port}
      # 设置服务实例info path
      status-page-url-path: /info
      # 设置服务实例健康检查path
      health-check-url-path: /health
      # 服务实例的续约到期时间（默认90秒），也就是心跳的最大等待时间。开发阶段调小
      lease-expiration-duration-in-seconds: 10
      # 服务实例的续约更新时间间隔（默认30秒），也就是心跳时间。开发阶段调小
      lease-renewal-interval-in-seconds: 6
      metadata-map:
        # 服务实例权重 默认100
        weight: 100
        # 服务actuator的管理port，如果设置了的话，Turbine监控台就获取不到对应服务的hystrix.stream。这里就需要设置，Turbine会读取这个端口。
        management.port: ${management.port:${server.port}}
        # 服务actuator的管理path，这里主要是为了服务治理页面能够动态读取。
        management.path: ${management.context-path}

# hystrix配置
hystrix:
  threadpool:
    default:
      coreSize: 100
      maxQueueSize: 1000
      queueSizeRejectionThreshold: 800
  command:
    default:
      execution:
        isolation:
          thread:
            # 断路器的超时时间,断路器的超时时间需要大于ribbon的超时时间，不然不会触发重试。
            timeoutInMilliseconds: 60000

# ribbon配置
ribbon:
  eager-load:
    enabled: true
    clients: pchain-admin,pchain-usc-service,pchain-auth-server
  # ribbon请求连接的超时时间 默认2秒 ms
  ConnectTimeout: 5000
  # 请求处理的超时时间 默认5秒 ms
  ReadTimeout: 5000
  # 对所有操作请求都进行重试,不配置这个MaxAutoRetries不起作用 默认false
  OkToRetryOnAllOperations: true
  # 对当前实例的重试次数 默认0
  MaxAutoRetries: 1
  # 切换实例的重试次数 默认1
  MaxAutoRetriesNextServer: 2
  # 自定义的ribbon负载均衡策略 默认com.netflix.loadbalancer.AvailabilityFilteringRule
  NFLoadBalancerRuleClassName: com.pchain.common.ribbon.XlabelWeightMetadataRule
  # 从注册中心刷新servelist的时间 默认30秒 ms
  ServerListRefreshInterval: 15000


feign:
  hystrix:
    enabled: true
  client:
    config:
      feignName:
        connectTimeout: 5000
        readTimeout: 5000
  compression:
    request:
      enabled: true
    response:
      enabled: true
